In [4]:
import numpy as np
list_arr=[i for i in range(0,100)]
np_arr=np.arange(100)
print(list_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
print(np_arr.itemsize)

print(np_arr.itemsize * np_arr.size)

4
400


In [10]:
import sys
a=10
print(sys.getsizeof(a))

print(sys.getsizeof(a)* len(list_arr))

28
2800


In [10]:
import time
import numpy as np
size=100000
def add_list():
    
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+b[i] for i in range(size)]
    t2=time.time()
    return(t2-t1)
def numpy_addlist():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return(t2-t1)
t_list=add_list()
np_list=numpy_addlist()
print("list=",t_list*1000)
print("numpylist=",np_list*1000)

list= 27.898073196411133
numpylist= 0.9980201721191406


In [11]:
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
a=[1,2,3,'c',4.5]
b=np.array(a)
print(b)
#unlike array numpy can hold homogenous data types thas why its convrted into string

['1' '2' '3' 'c' '4.5']


In [13]:
import numpy as np
a=[1,2,3,4.5]
b=np.array(a,dtype=int) 
print(b)

[1 2 3 4]


### functions of 
np.ones(),
np.zeros(),
np.full(),
np.empty()

In [15]:
import numpy as np
a=[1,2,3,4.5]
b=np.array(a*3)
b

array([1. , 2. , 3. , 4.5, 1. , 2. , 3. , 4.5, 1. , 2. , 3. , 4.5])

In [17]:
import numpy as np
a=[1,2,3,4.5]
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [18]:
import numpy as np
a=[1,2,3,4.5]
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [23]:
import numpy as np
a=[1,2,3,4.5]
b=np.full(3,2,dtype=int) 
b

array([2, 2, 2])

In [33]:
import numpy as np
b=np.empty(3) 
b

array([1., 1., 1.])

In [36]:
import numpy as np
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
import numpy as np
f= np.empty(4, dtype = int)
print(f)

[-2017592953  -185899277  1457566972  -711787432]


In [50]:
import numpy as np
a=np.zeros(10,dtype=int)

In [52]:
a[4]=1
for i in a:
    print(i ,end=' ')

0 0 0 0 1 0 0 0 0 0 

In [47]:
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [48]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
import numpy as np
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
import numpy as np
a=np.linspace(2,10)
print(a[1]-a[0])
print(a[2]-a[1])

0.16326530612244916
0.16326530612244872


In [2]:
import numpy as np
a=np.linspace(2,10,5,dtype=int,endpoint=False)
a

array([2, 3, 5, 6, 8])

In [7]:
import numpy as np
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
import numpy as np
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
import numpy as np
a=np.random.rand(3)
a
#the random value is generated thts between 0 to 1

array([0.62677384, 0.53654942, 0.01560464])

In [11]:
import numpy as np
a=np.random.rand(3,2)
a

array([[0.54140059, 0.10984497],
       [0.14317677, 0.77140888],
       [0.08593671, 0.89554489]])

In [16]:
import numpy as np
a=np.random.rand(10)*10
a

array([7.1244961 , 6.24016899, 4.85778019, 9.50599975, 3.26261713,
       6.96832696, 3.57715856, 0.87712182, 8.09624596, 3.30670404])

In [15]:
import numpy as np
a=np.random.randint(5,10)
a

9

In [20]:
print(np.random.rand())

0.10809803795380468


In [22]:
print(np.random.randint(10, 4))
# the value can't go like high to low

ValueError: low >= high

In [24]:
import numpy as np
print(np.random.randint(10,size=(4,4)))

[[4 9 2 7]
 [8 4 6 3]
 [1 9 1 6]
 [5 7 1 8]]


In [17]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [4]:
import numpy as np
a=np.arange(9,50,dtype=int)
for i in a:
    print(i,end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [17]:
import numpy as np

a=np.linspace(0,5,num=9,endpoint=False)

for i in a :
     if i!=0.0 and i!=5.0 :
        
        print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [8]:
start_point=float(5/9)
start_point

0.5555555555555556

In [18]:
import numpy as np

li=[1,2,3,4,5]
a=np.array(li)
print(li)
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [20]:
print(a.data)
print(a.dtype)
print(a.shape)
print(a.strides)

int32
(5,)
(4,)


# slicing in numpy arrays

In [23]:
import numpy as np
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
d2_arr=np.array(li)
print(d2_arr.shape)
print(d2_arr.strides)

(4, 4)
(16, 4)


In [24]:
print(li[2][1])
print(d2_arr[2,1])

10
10


In [27]:
print(d2_arr[2][:3])
print(d2_arr[2,:3])

[ 9 10 11]
[ 9 10 11]


In [29]:
print(d2_arr[:3,2])

[ 3  7 11]


In [37]:
print(d2_arr[0,:4])

[1 2 3 4]


In [42]:
print(d2_arr[2:4,1:3],end="")

[[10 11]
 [14 15]]

In [41]:
print(d2_arr[2:4][1:3])

[[13 14 15 16]]


In [1]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print()
print(input_)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
a=input_[2 ,:3]
for i in a:
    print(i,end=' ')

11 12 13 

In [7]:
b=input_[1:4,3]
for i in b:
    print(i,end=' ')

9 14 19 

In [10]:
c=input_[2:4]
for i in c:
    for j in i:
        print(j,end=' ')

11 12 13 14 15 16 17 18 19 20 

In [4]:
a=input_[1:3,1:3]
for i in a:
    for j in i:
        print(j,end=" ")

7 8 12 13 

In [79]:
import numpy as np
x=[1,2,0,0,4,0]
a=np.array(x)
z=np.logical_not(a)
for i in z:
    if i == False:
        print(id(i),end=" ")

140725751255928 140725751255928 140725751255928 

In [4]:
import numpy as np
x=[1,2,0,0,4,0]
a=np.array(x)
ind=np.where(a>0)
a=list(ind)
for i in ind:
    for j in i:
        print(j,end=" ")

0 1 4 

In [6]:
import numpy as np
a=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
ind=np.where(a%3==0)
for i in ind:
    for j in i:
        print(j,end=' ')

1 4 7 

In [29]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ind=np.where(a%2 !=0)
for i in ind:
    for j in i:
        a[j]=-1
a=list(a)
for i in a:
    print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [32]:
import numpy as np
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
b=np.argmax(a)
a[b]=0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


In [36]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num1=a[a<4]
num2=a[(a>7)]
print(num1)
print(num2)

[1 2 3]
[ 8  9 10]


In [39]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num1=a[a<4]
num2=a[a>7]
num3=np.concatenate((num1, num2), axis=0)
print(num3)

[ 1  2  3  8  9 10]


In [50]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[2:8]=a[2:8]*-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [48]:
import numpy as np
arr=np.arange(1,11)
arr[(arr>=3) & (arr<=8)]=arr[(arr>=3) & (arr<=8)]*-1
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [88]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
a=np.where(height>155)
b=list(a)
for i in a:
    for j in i:
        print(age[j],height[j])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


# boolean indexing of 2D array

In [2]:
import numpy as np
a=np.random.randint(1,30,(5,6))
a

array([[16, 14,  2, 19,  4, 25],
       [19, 18,  3, 13, 22, 20],
       [17,  5, 29, 17,  1,  9],
       [24, 17, 25, 15,  4, 29],
       [28,  4,  6, 21, 16, 17]])

In [3]:
a>20

array([[False, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False,  True, False, False, False],
       [ True, False,  True, False, False,  True],
       [ True, False, False,  True, False, False]])

In [4]:
a[a>20]=100
a

array([[ 16,  14,   2,  19,   4, 100],
       [ 19,  18,   3,  13, 100,  20],
       [ 17,   5, 100,  17,   1,   9],
       [100,  17, 100,  15,   4, 100],
       [100,   4,   6, 100,  16,  17]])

In [6]:
b=a
bool_arr=b[:,4] ==100
print(bool_arr)

[False  True False False False]


In [7]:
b[bool_arr,4]=99
b

array([[ 16,  14,   2,  19,   4, 100],
       [ 19,  18,   3,  13,  99,  20],
       [ 17,   5, 100,  17,   1,   9],
       [100,  17, 100,  15,   4, 100],
       [100,   4,   6, 100,  16,  17]])

In [60]:
import numpy as np
a=np.array([[21,20,19,18,17],
  [16,15,14,13,12],
  [11,10,9,8 ,7],
  [ 6,5,4,3,2]])
sort_arr=a[::-1]
print(sort_arr)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


# Broadcasting

In [66]:
import numpy as np
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3))
print(a)
print(b)

[[6 5 7]
 [8 2 3]
 [8 7 8]]
[9 9 4]


In [67]:
c= a + b
print(c)

[[15 14 11]
 [17 11  7]
 [17 16 12]]


In [68]:
import numpy as np
a=np.random.randint(1,10,(3,2))
b=np.random.randint(1,10,(2,3))
print(a)
print(b)

[[2 8]
 [7 1]
 [7 1]]
[[5 1 5]
 [6 3 6]]


In [69]:
b=np.transpose(b)
b

array([[5, 6],
       [1, 3],
       [5, 6]])

In [70]:
c=a-b
c

array([[-3,  2],
       [ 6, -2],
       [ 2, -5]])

# resize() reshape()

In [73]:
import numpy as np
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,1))
print(a)
print(b)

[[3 4 5]
 [2 6 1]
 [5 2 6]]
[[2]
 [6]
 [1]]


In [74]:
c=a+b
c

array([[ 5,  6,  7],
       [ 8, 12,  7],
       [ 6,  3,  7]])

In [75]:
import numpy as np
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(3,1))
print(a)
print(b)

[[5 6 1]]
[[2]
 [4]
 [7]]


In [76]:
c=a*b
c

array([[10, 12,  2],
       [20, 24,  4],
       [35, 42,  7]])

In [77]:
import numpy as np
a=np.random.randint(1,10,(1,3))
b=np.random.randint(1,10,(1))
print(a)
print(b)

[[6 3 5]]
[7]


In [78]:
c=a*b
c

array([[42, 21, 35]])

In [6]:
import numpy as np
import csv
with open("C:/Users/biswa/OneDrive/Desktop/year2017.csv") as file_obj:
    file_data=csv.DictReader(file_obj)
    killed=[]
    wounded=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
    np_killed=np.array(killed)
    np_wounded=np.array(wounded)
    np_country=np.array(country)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    killed_wounded=np_killed+np_wounded
    bool_arr=np_country == 'India'
    ans=killed_wounded[bool_arr]
    print(sum(ans))

1167.0


In [12]:
import numpy as np
import csv
with open("C:/Users/biswa/OneDrive/Desktop/terrorismData.csv") as file_obj:
    file_data=csv.DictReader(file_obj)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row["Killed"])
        country.append(row["Country"])
    np_killed=np.array(killed)
    np_country=np.array(country)
    
    np_killed[np_killed =='']='0.0'
    
    np_killed=np.array(np_killed,dtype=float)
    bool_arr= np_country == 'United States'
    for i in np_killed[bool_arr]:
        print(int(i))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


In [17]:
import numpy as np
import csv
with open("C:/Users/biswa/OneDrive/Desktop/terrorismData.csv") as file_obj:
    file_data=csv.DictReader(file_obj)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row["Killed"])
        country.append(row["Country"])
    np_killed=np.array(killed)
    np_country=np.array(country)
    
    np_killed[np_killed =='']='0.0'
    
    np_killed=np.array(np_killed,dtype=float)
    bool_arr= np_country == 'United States'
    ans = np_killed[bool_arr]
    print(int(sum(ans)))

3771


In [23]:

import numpy as np
import csv
with open("terrorismData.csv") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    year=[]
    month=[]
    day=[]
    for row in file_data:
        year.append(row["Year"])
        month.append(row["Month"])
        day.append(row["Day"])
    np_year=np.array(year,dtype='int')
    np_month=np.array(month,dtype='int')
    np_day=np.array(day,dtype='int')
    
    np_day=np_day[np_month==1]
    np_year=np_year[np_month==1]
    np_day=np_day[np_year==2010]
    
    count=0
    for i in np_day:
        if i>=1 and i<=31:
            count+=1
    print(count)

IndexError: arrays used as indices must be of integer (or boolean) type

In [25]:
with open("C:/Users/biswa/OneDrive/Desktop/terrorismData.csv") as file_obj:
    
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    days=[]
    for row in file_data:
        days.append(row['Day'])
    np_days=np.array(days, dtype=float)
    s=np_days[(np_days>=10) & (np_days<=20)]
    print(s.shape[0])

66330


In [33]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv
with open("C:/Users/biswa/OneDrive/Desktop/terrorismData.csv") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    
    killed=[]
    wounded=[]
    city=[]
    group=[]
    for row in file_data:
        if row['Year']=='1999':
            if row['Month']=='5' or row['Month']=='6' or row['Month'] =='7':
                if 'Unknown' not in row['City']:
                    if 'Unknown' not in row['Group']:
                        if 'Jammu and Kashmir' in row['State']:
                            killed.append(row['Killed'])
                            wounded.append(row['Wounded'])
                            city.append(row['City'])
                            group.append(row['Group'])
    np_killed=np.array(killed)
    np_wounded=np.array(wounded)
    np_city=np.array(city)
    np_group=np.array(group)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    
    np_killed=np.array(np_killed,dtype=float)
    np_wounded=np.array(np_wounded,dtype=float)
    casuality=np_killed+np_wounded
    max_casuality=casuality.max()
    index1=casuality.argmax()
    print(int(max_casuality),city[index1],group[index1])

22 Kargil District Separatists


In [35]:
with open('C:/Users/biswa/OneDrive/Desktop/terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    state=[]
    for row in file_data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        state.append(row['State'])
    np_killed=np.array(killed)
    np_killed[np_killed=='']='0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(wounded)
    np_wounded[np_wounded=='']='0'
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_killed+np_wounded, dtype='int')
    count=0
    for i in range(len(state)):
        if state[i]=='Chhattisgarh' or state[i]=='Odisha' or state[i]=='Jharkhand' or state[i]=='Andhra Pradesh':
            count+=np_casuality[i]
    print(count)

5628


In [ ]:
with open('../input/terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])